.gitmodules
new file:   photolocation-skill
new file:   pickup-line-skill
new file:   ping-skill
new file:   spacelaunch-skill
new file:   sun-skill
new file:   wallpaper-skill
new file:   wifi-management-skill
=> 	new file:   cleverbot-skill

.gitmodules, README.md
Hey people,
cause i like clementine more than amarok, i made me a little fork. Also some keywords where added.
Hope it's working and being usefull for others as well.. 
regards
=> add clementine-skill

README.md
=> Typos in README files

.gitmodules
https://github.com/btotharye/mycroft-homeassistant
Used to control home assistant with mycroft.
Currently working
=> adding in home assistant skill

.gitmodules, README.md
https://github.com/btotharye/mycroft-twitter-skill
twitter-skill
Control different aspects of twitter with mycroft.
Currently working
=> Twitter skill

.gitmodules, README.md
Reverts MycroftAI/mycroft-skills#100
=> Revert "Twitter skill"

.gitmodules
Reverts MycroftAI/mycroft-skills#99
=> Revert "adding in home assistant skill"

.gitmodules
Reverts MycroftAI/mycroft-skills#103
=> Revert "Revert "adding in home assistant skill""

.gitmodules, README.md
Reverts MycroftAI/mycroft-skills#102
=> Revert "Revert "Twitter skill""

.gitmodules
deleted:    HOMEASSISTANT-skill
new file:   HomeAssistant-skill
=> 	modified:   .gitmodules

.gitmodules
Reverts MycroftAI/mycroft-skills#107
=> Revert "Update .gitmodules"

.gitmodules
modified:   .gitmodules
renamed:    HomeAssistant-skill -> homeassistant-skill
renamed:    TWITTER-skill -> twitter-skill/TWITTER-skill
=> 	Renaming submodules

.gitmodules, README.md
The default skill hello world isn't in the repo.
=> Add missing skill hello-world

.gitmodules, README.md
modified:   .gitmodules
modified:   README.md
new file:   gpio-example-skill
=> 	Added GPIO Example skill

.gitmodules, README.md
=> Add skill-playback-control

.gitmodules, README.md
Skill repo: https://github.com/ChristopherRogers1991/mycroft-irsend
Short name: irsend
Description: Allows the user to control devices via lirc's [irsend](http://www.lirc.org/html/irsend.html).
Development Status: Working.
=> Add irsend skill

.gitmodules, README.md
Repo URL : [https://github.com/EngelOfChipolata/Mycroft-Slack-skill](https://github.com/EngelOfChipolata/Mycroft-Slack-skill)
Name : Slack Skill
Description : Send and read Slack messages with Mycroft !
Development Status : Sending is working, other features coming soon !
=> Adding Slack skill for submission on skills list

.gitmodules, README.md
did this skill the other day, is working 100% as of today.
=> adding my skill skill-radio-rne to main upstream repo

.gitmodules, README.md
Adding skill to test new releases
=> Release test

.gitmodules
This adds the release test skill to the repo.
=> Add release test skill

.gitmodules
Also remove duplicate from the .gitmodules file
Resolves #132
@AIIX would you mind checking that the url's in the `.gitmodules` file are correct?
=> Update url for AIIX plasma skills

.gitmodules, README.md
**Repo URL:** https://github.com/ChristopherRogers1991/mycroft-speedtest.git
**Name:** speedtest
**Description**: This skill runs a speedtest with an output of ping, download, and upload speeds.
**Development Status:** working
=> Adding new skill: speedtest

.gitmodules, README.md
Hi,
I developed a new skill to support openhab. It's the first version and is working. At the moment supports few commands (ON,OFF) and it requires more tests.
repo: https://github.com/mortommy/skill-openhab
name: openhab-skill
desc: Openhab skill for Mycroft
status: working but under construction
Thank you.
=> openhab-skill

.gitmodules, README.md
Add AIML fallback skill (original by jarbasAI, minor cleanup by me)
=> Add AIML Fallback

.gitmodules
=> removed old release-test submodule

.gitmodules, .travis.yml, test-requirements.txt
fixing the broke submodules also should resolve issue #154
=> fixing broke submodules

.gitmodules, README.md
Provides basic mycroft help questions and is used for the bot backend atm.
=> updating for basic help skill

.gitmodules, README.md
Repo URL: https://github.com/wligtenberg/coin-flip-skill
Name: coin-flip
Description: This skill flips a virtual coin
Development Status: working
=> Add coin-flip skill

README.md
pop culture references skill, quotes and sound files
=> add easter eggs skill

.gitmodules, README.md
This skill integrates Plasma 5 Desktop Audio Controls with Mycroft which enables users to Increase/Decrease Volume of Master and Capture on the Desktop.
```
```
=> New Skill: audio-control-plasma

.gitmodules, README.md
Check the version of mycroft-core.
**Usage:**
```
Check version
Check platform build
```
Planning on being included as a default skill.
=> Add version checker skill

.gitmodules, README.md
=> Added Angry Beanie Skill

.gitmodules, README.md
skill-caffeinewiz: working
Provides the caffeine content of various drinks on request.
https://github.com/reginaneon/skill-caffeinewiz.git
```
+[submodule "skill-caffeinewiz"]
+	path = skill-caffeinewiz
+	url = https://github.com/reginaneon/skill-caffeinewiz.git
```
=> Adding a new finished skill: CaffeineWiz

.gitmodules, README.md
Calculator skill, can do running calculations through conversational context.
- [x ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
- [ x] Skill has been tested and works
- [x ] README.md has been updated with the following:
```
+	path = calculator-skill
+	url = https://github.com/TREE-Edu/calculator-skill.git
```
- [x ] README.md has been updated with your skill phrase and description
=> Adding Calculator Skill

.gitmodules, README.md
**it can set multiple timers, cancel timers, get status of timers. 
- [x ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
- [x ] Skill has been tested and works
- [x ] README.md has been updated with the following:
```
```
- [x ] README.md has been updated with your skill phrase and description
=> added a skill using mycroft-timer

.gitmodules, README.md
This Skill reads the Australian news. 
It's a basic Skill - it's my first Mycroft Skill. 
```
```
=> Add skill-australian-news

.gitmodules, README.md
=> added play some music skill

.gitmodules, README.md
The skill allows a user to control the mycroft plasmoid itself via voice
```
```
=> New Skill: plasma-mycroftplasmoid-control

.gitmodules, README.md
Listen to Deutschlandfunk (German national public radio) and query the schedule.
```
```
=> Add Deutschlandfunk skill

.gitmodules, README.md
Fallback for when Mycroft doesn't know the answer
This will be used instead of the current, hard-coded "Sorry, I didn't catch that. Please rephrase your request."
=> Add Unknown Fallback

.gitmodules, README.md
This is a duplicate of my other skill "play-some-music".  I found that a few users had trouble installing play some music using voice commands if they already had already installed the Pandora skill.  I also think that this is a better name for the skill.
```
```
=> added skill-internet-radio

.gitmodules, README.md
A skill that controls the mark 1 enclosure
you can control the mark 1 enclosure. so far it's the brightness and eye color
```
```
=> mycroft-mark-1

.gitmodules, README.md
Controls Kate Editor - Switching tabs, creating new documents, closing documents, splitting views, saving documents etc
```
```
=> New skill: kde-kate-control

.gitmodules
The dashes allow parsing assumptions used by MSM function properly
=> Add dashes to submodule names

.gitmodules
Remvoed several skills that are not wanted in the repo for various reasons:
* wink-smart-home -- never completed, replaced by mycroft-wink-iot
* earth-orbit-pic-skill -- bad add, duplicate of near-earth-object-tracker
* play-some-music -- was renamed by creator to internet-music
* skill-wolfram-alpha -- became fallback-wolfram-alpha
=> Remove dead skills, consistent lowercasing in name

.gitmodules, README.md
**Control lights via the Wink ecosystem
```
```
=> Adding the official Wink IoT skill

.gitmodules, README.md
Remove mopdiy-media-player, (was replaced ans superseded by "mopidy_skill")
=> Remove mopidy-media-player

README.md
=> Undo and fuzzy lists features added

.gitmodules, README.md
- [ x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
- [ x] Skill has been tested and works
- [ x] README.md has been updated with the following:
```
```
- [ x] README.md has been updated with your skill phrase and description
=> Added skill mosquito speak

.gitmodules
Mycroft will play a farting sound when requested or at random intervals.
This is just a fun skill that should generate a laugh or two and then probably never be used again.
```
+[submodule "FartingSkill"]
+	path = skill-farting
+	url = https://github.com/aussieW/skill-farting.git
```
=> Initial commit.

.gitmodules, README.md
**That skill communicates with an ESP8266 with multiple protocol (http, websocket, mqtt) in the context of home automation.**
```
+[submodule "esp8266-skill"]
+	path = esp8266-skill
+	url = https://github.com/Dark5ide/esp8266-skill.git
```
=> Add esp8266-skill

README.md
**This change is to update the info in README for a bitcoin-price skill that has already been incorporated into mycroft-skills.  This skill now works, and its submodule can be updated to point to the most recent commit.  Thank you.
=> Updated bitcoin-price info.

.gitmodules, README.md
Search for nearby Places for Mycroft on Plasma (Search For Restaurants, Hotels, Parks, Hospitals and other Places of Interest), Uses Mozilla Location Services and Here API, 
* Requires Updated Mycroft Plasmoid To Display Results
```
```
=> Added whats-nearby skill

.gitmodules, README.md
Lets the user request playback of any music or video available free of charge. Version 1.0
```
```
=> Adding NGI  AVmusic skill

.gitmodules, README.md
* has Mycroft pick a random number
My kids love this. They try to see who gets closer.
just say 'pick a number'
* a simple skill but would like it to eventually ask a range  "pick number between x and y"
- [X ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
- [ X] Skill has been tested and works
- [X ] README.md has been updated with the following:
```
+[submodule "number-generator"]
+path = number-generator
+url = https://github.com/angry-frog/number-generator-skill
```
- [X ] README.md has been updated with your skill phrase and description
=> number generator skill

.gitmodules, README.md
This skill queries Kickstarter for the current pledge amount of a project
```
```
=> Add Kickstarter Tracker Skill

.gitmodules, README.md
**This skill tells the federal government office closings as retrieved from OPM site.
```
+[submodule "skill-federal-closings"]
+	path = skill-federal-closings
+	url = https://github.com/mason88/skill-federal-closings
```
=> Request to add new federal closings listings skill

.gitmodules, README.md
**Add better Jokes skill
```
+[submodule "tjoen-better-jokes"]
+	path = tjoen-better-jokes
+	url = https://github.com/tjoen/skill-better-jokes
```
=> Adding Better jokes

.gitmodules
=> persona fallback

.gitmodules, README.md
Allow the user to select their favourite podcasts in the home.mycroft.ai settings and listen to the latest episodes of those podcasts.
```
```
=> added podcast-skill

.gitmodules, README.md
Will speak a quote from Confucius when asked. Will also provide a humorous quote is requested.
```
```
=> Added new skill "skill-confucius-say" and updated README.md to include "skill-farting".

.gitmodules, README.md
Repeats recent audio transriptions and text to speech outputs
=> Add repeat recent skill

.gitmodules, README.md
Player for streaming media from Subsonic Media Player
```
```
=> Include subsonic media skill in readme

README.md
I messed up and broke formatting of the README.md.  This fixes it.
=> Fix formatting of README.md

.gitmodules, 00__skill_template/requirements.sh
Execute `nmap` portscan with `scan TARGET IP`
```
+[submodule "skill-nmap"]
+	path = skill-nmap
+	url = github.com/Nhoya/skill-nmap.git
```
=> Nmap skill

.gitmodules
I fixed the submodule link and renamed the nmap skill from skill-nmap to a more clear nmap-skill
=> Fix and rename nmap skill submodule

.gitmodules
=> 18.02 fallback wolfram alpha

.gitmodules
Re-add skill-personal
No reviewing or merging needed
=> Restore skill-personal

.gitmodules
Readd skill-ip after updated tests
No review needed.
=> Add skill-ip

.gitmodules, DEFAULT-SKILLS
Readd skill-playback-control.
No review needed.
=> 18.02 skill playback control

.gitmodules, README.md
Re-add skill-configuration.
No review/merge needed
=> Re-add skill configuration

.gitmodules
Add mycroft-date-time to 18.02
=> Re-add mycroft-date-time

.gitmodules
Restore mycroft-volume in 18.02 branch.
=> Add mycroft-volume

.gitmodules
Restore skill-installer, Review and merge not needed.
=> Add skill-installer

.gitmodules, README.md
Add skill-npr-news into 18.02 branch
=> Re-add skill-npr-news

.gitmodules, README.md
Add skill-singing to 18.02 branch
=> Restore skill-singing

.gitmodules, README.md
**Skill for mycroft to get the word of the day. 
- [ X ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
- [ X ] Skill has been tested and works
- [ X ] README.md has been updated with the following:
```
```
- [ X ] README.md has been updated with your skill phrase and description
=> Add: Word of the Day skill

.gitmodules
Add skill alarm to 18.02 branch
=> Add skill-alarm

.gitmodules
=> Add skill-pairing to 18.02

.gitmodules
Re-add skill-support into 18.02 branch
=> Restore skill-support

.gitmodules
Add skill-wiki in 18.02 branch
=> Add skill-wiki

.gitmodules
=> Add skill-release-test

.gitmodules, README.md
Restore skill-reminder in 18.02 branch
=> Add skill-reminder

.gitmodules
Add skill-weather to 18.02 branch
=> Add skill-weather

.gitmodules
=> Add skill-spelling

.gitmodules, README.md
=> Add mycroft-timer

.gitmodules, README.md
Restore spotify-skill with single test case.
=> Add spotify-skill with simple test

.gitmodules
Restore pandora-skill, currently without tests.
=> Add pandora-skill

.gitmodules
Restore mark1-demo skill to repo.
=> Add mark1-demo skill

.gitmodules
=> Add Mycroft-Mark-1

.gitmodules
=> 18.02 mycroft speak

DEFAULT-SKILLS
=> remove comment for mycroft-timer to be default

.gitmodules
This PR adds the new skill, [translate-skill](https://github.com/jcasoft/translate-skill), to the skills repo.
Allow to translate phrases into other languages:
supported languages:
english, spanish, french, italian, portuguese, dutch, german, swedish, hungarian, polish, norwegian, danish, romanian, slovak, catalan, chinese, japanese, korean, greek, vietnamese, turkish, finnish and arabic
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.4</sub>
=> Add translate-skill

.gitmodules, README.md
It manages the Home Assistant api and allows control of IoT and smarthome devices
```
```
=> updating to add home assistant skill

.gitmodules, README.md
Control Plasma 5 Desktop Activities Feature - Create new activities, switch between activities, remove and stop activities, display available activities
```
```
=> Add Plasma Actvities Skill

.gitmodules
add persona-fallback to the new skills branch
```
```
=> persona-fallback

.gitmodules, README.md
the skill allows to control openHAB objects from mycroft AI
```
```
=> Add openhab-mycroft skill

.gitmodules, README.md
Discover and control WeMo devices
```
```
=> WeMo skill

.gitmodules, README.md
Score reports the latest score for MLB teams, including live.
```
+[submodule "deej-score"]
+	path = deej-score
+	url = https://github.com/deejcunningham/skill-score
```
=> Skill: Score

.gitmodules, README.md
This skill integrates Plasma 5 Krunner with Mycroft which enables users to search their local desktop for files, images, recent documents, bookmarks and utilize other krunner plugins. 
```
```
=> Add Krunner Search Skill to 18.02

.gitmodules, README.md
This skill detects the number of persons in front of a webcam. It uses tensorflow for object detection.
The object detection module is to be downloaded from [(https://github.com/tensorflow/models/tree/master/research/object_detection)]
Checklist:
[x ] Used Meta Editor to generate the skill README
[x ] Skill has been tested and works
[ x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
[x ] README.md has been updated with the following:
+[submodule "person detector"]
+	path = person-detector
+	url = https://github.com/patilaum/mycroft-person-detect-skill.git
- [x ] README.md has been updated with your skill phrase and description
=> new skill person detection

.gitmodules, README.md
Gives a random today in history event
```
```
=> adding in today in history skill

.gitmodules
This PR adds the new skill, [chatbot](https://github.com/forslund/fallback-aiml), to the skills repo.
This is a AIML fallback using the Alice chatbot files. This is based on the works of [JarbasAI](https://github.com/JarbasAI) to work stand-alone in the current mycroft-core (2017-08-09). Over the time it's been augmented by Nielstron and EazyAlvaro.
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>
=> Add chatbot

.gitmodules
This PR adds the new skill, [routine](https://github.com/ChristopherRogers1991/mycroft_routine_skill), to the skills repo.
Create named rountines, which are lists of Mycroft commands, that can be run by name, and scheduled to run at particular times.
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>
=> Add routine

.gitmodules, README.md
This PR adds the new skill, [pianobar-skill](https://github.com/MycroftAI/pianobar-skill), to the skills repo.
Pandora provides dynamically generated internet radio streams.  Streams are
influenced by the the traits of the music played and the songs you like
or skip.
Using this skill does require a [Pandora.com](https://pandora.com) account.
Sign-up is free with ad-supported streams.
This skill should work with Mycroft version 0.9.1 +
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>
=> Add pianobar-skill

.gitmodules
This PR adds the new skill, [what-can-you-do](https://github.com/luke5sky/what-can-you-do-skill), to the skills repo.
It tells you what you can do with Mycroft (some examples)
and lists the installed skills (if you want).
Just a simple script but i missed it
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>
=> Add what-can-you-do

.gitmodules, README.md
A simple wrapper so Aircrack-ng can be used with Mycroft.
=> Getting ready for a pull request

.gitmodules
This PR adds the new skill, [rss-reader](https://github.com/backassward/rss-reader-skill), to the skills repo.
This skill is a simple tool to get updates from your favorite news sources.
the main features are:
* manage your feed subscriptions from your [dashboard](https://home.mycroft.ai/),
* ask Mycroft to check if new articles have been published,
* ask Mycroft to read the titles and other information for you.
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>
=> Add rss-reader

.gitmodules
This PR adds the new skill, [cocktails](https://github.com/forslund/skill-cocktail), to the skills repo.
The skill reads the drink mixing instructions for you and lists all the required ingredients for your favourite drinks.
The skill uses the cocktail and drink database  https://thecocktaildb.com.
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>
=> Add cocktails

.gitmodules
This PR adds the new skill, [desktop-control](https://github.com/TREE-Ind/desktop-control), to the skills repo.
A Mycroft AI skill to enable keyboard and mouse manipulation using natural language.
<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>
=> Add desktop-control

.gitmodules
Control and Navigate Plasma-Mycroft Plasmoid and Additional Internal Functions
Note: Re adding due to previous failed build skill-test and change in kde defaults
```
```
=> Add Plasma-mycroft-applet-control

DEFAULT-SKILLS.mycroft_mark_1, DEFAULT-SKILLS.picroft
Restore missing core default skills to the DEFAULT-SKILLS.mycroft-mark-1
=> Restore core skills to mark-1 default skills
